### PR TITLE
Contributions guidelines

### PR DESCRIPTION
**Pull request by lbenie**
As said in issue #11

### CODE REVIEW

**Comment by azachar** [comment]
Hey lbenie, 
Please squash your 2 commits into one before providing PR. If you do not know how to do it, read this http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit http://programmers.stackexchange.com/questions/263164/why-squash-git-commits-for-pull-requests

Also it would be cool to mentioned it the doc :)

What do you think?

A.

**Comment by azachar** [comment]
Sorry to bug you with it, but let's do it right way..

**Comment by lbenie** [comment]
@azachar thanks will do it in an instant

never knew how to do that !

**Comment by azachar** [comment]
You are welcome! :)

**Comment by lbenie** [comment]
@azachar it should be fine now :smile:

**Comment by azachar** [comment]
Thanks, great job!

**Pull request merged**
